name: Validate

on:
  workflow_call:

permissions: {}

jobs:
  validate:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: ['5.4', 'latest']

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Install PHP
        uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # 2.37.1
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Install dependencies
        run: composer update --no-interaction --no-progress

      - name: Validate Composer installation
        run: composer validate --no-check-all --strict
